remove deprecated GitHub Actions Command and some improvements
Perl/perl5 pull request #18227
Opened 2020-10-10 07:22 UTC by shogo82148

This pull request fixes the following warning message.

> https://github.com/Perl/perl5/actions/runs/296812857
>
> The `add-path` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

And replace `actions/checkout@master` into `actions/checkout@v2`.
Because GitHub recommends use tag names rather than branch names.

2020-10-12 20:52 UTC, atoomic requested changes

2020-10-12 20:52 UTC, atoomic commented on .github/workflows/testsuite.yml
> +          choco config set cacheLocation "${{ github.workspace }}\choco-cache"
Nice improvement

2020-10-12 20:52 UTC, atoomic commented on .github/workflows/testsuite.yml
> +      - uses: actions/checkout@v2
Indeed better to use v2 when we can

2020-10-12 20:52 UTC, atoomic commented on .github/workflows/testsuite.yml
> +          echo "C:\strawberry\c\bin`nC:\strawberry\perl\site\bin`nC:\strawberry\perl\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
I think there is an alternate syntax much easier to read. But this is correct

2020-10-12 20:52 UTC, atoomic commented on .github/workflows/testsuite.yml
> -      - run: git config --global core.autocrlf false
This line was removed but then added to the very long line later. Wouldn't it be better to preserve it there?

2020-10-13 01:02 UTC, shogo82148 commented on .github/workflows/testsuite.yml
> -      - run: git config --global core.autocrlf false
Git on windows is not the same thing as git on cygwin.
This line calls the git on windows, and gives no effect git on cygwin.

2020-10-13 15:05 UTC, atoomic approved these changes
@shogo82148 this looks good to me, do you mind squashing all of this as a single commit before I can merge it?
thanks

2020-10-13 15:07 UTC, merged

2020-10-13 15:08 UTC, atoomic commented
@shogo82148 do not bother squashing, the option is directly available from GitHub.
You do not need to do it, it's now merged.
Thanks for the updated/improved workflow

2020-10-13 16:31 UTC, shogo82148 commented
Your welcome!