utf8_length: Fix undefined C behavior
Perl/perl5 pull request #18878
Opened 2021-06-11 04:25 UTC by khwilliamson

In C the comparison of two pointers is only legal if both point to
within the same object, or to a virtual element one above the high edge
of the object.

The previous code was doing an addition potentially outside that range,
and so the results would be undefined.

2021-06-11 04:44 UTC, tonycoz requested changes

2021-06-11 04:44 UTC, tonycoz commented on utf8.c
> +        expected_byte_count = UTF8SKIP(s);
This line isn't needed.

2021-06-11 04:45 UTC, tonycoz commented on utf8.c
> +        expected_byte_count = UTF8SKIP(s);
urr, the line selection was a bit off, that assignment to expected_byte_count isn't needed

2021-06-29 23:26 UTC, khwilliamson commented
That line was a relic from a previous incarnation

2021-06-30 01:23 UTC, tonycoz approved these changes

2021-06-30 01:23 UTC, merged