Update README.haiku
Perl/perl5 pull request #18974
Opened 2021-07-10 14:28 UTC by thibaultduponchelle

Some more up to date informations about past/present notable difference/known problems.

2021-07-17 13:50 UTC, khwilliamson requested changes

2021-07-17 13:50 UTC, khwilliamson commented on README.haiku
> +Haiku file system has a limitation and does not store the access time.
Change to 'The Haiku file system...'

2021-07-17 13:50 UTC, khwilliamson commented on README.haiku
> +When using "stat", it will return always the local time,
Change to 'always return', as that is more idiomatic English

2021-07-17 13:50 UTC, khwilliamson commented on README.haiku
> +(like if "stat" was considered as an access).
Change 'like' to 'as if'

2021-07-17 13:50 UTC, khwilliamson commented on README.haiku
> +It is not the common implementation, but neither not considered false for POSIX.
I don't understand this sentence.  I think you're saying it is legal in POSIX, but not what one would expect. @Grinnz @jmacdotorg do you have good phrasing for this?

2021-07-17 13:50 UTC, khwilliamson commented on README.haiku
> +have then some unexpected results and need to be skipped (fixed in perl 5.36).
s/have then/thus have/

2021-07-17 13:50 UTC, khwilliamson commented on README.haiku
> +The ${^CHILD_ERROR_NATIVE} value seems to be the same than exit code.
'same than' is not good English.  Perhaps you mean 'same as' ?

2021-07-17 13:50 UTC, khwilliamson commented on README.haiku
> +A subtest of the F<cpan/Sys-Syslog/t/syslog.t> test was failing. This is due to Haiku
It has been fixed?

2021-09-21 14:53 UTC, thibaultduponchelle commented
I will close this for now since it needs some updates, has conflicts and I don't want to keep it "stale".

I appreciated the review and I will integrates them and reopen a clean PR when time comes :grinning:

2021-09-21 14:53 UTC, closed without merging