regex engine - rework node sizing logic and related functionality
Perl/perl5 pull request #20019
Opened 2022-07-30 18:40 UTC by demerphq

Currently there is a lot of brittle and opaque logic related to regex regnode (aka regop) sizing. 

* many objects share common node structures structures (eg, multiple different regnodes use `struct regnode_1`) and related macros.
*  there is a very confusing concept called `NEXTOPER(p)` heavily used in the regcomp.c (and somewhat used in regexec.c), this function looks like it does something like "find the next node in the compiled program which follows p", but in fact resolves to `p+1`, and is often used like this: `NEXTOPER(NEXTOPER(p))` to compute `p+2` for cases where the code assumes the regnode is of size 2. 
*  there is another concept called `regnext` which is a different kind of "next operator" for a node. The similarity in names with `NEXTOPER()` make it quite confusing what the difference is.
*  We have a utility array called `PL_regarglen` which can be used to look up how big a given opcode should be, but it does not handle all node types, only those of a constant size.
* There are other macros which can be used to find how big a variable length regnode is, but there is nothing programmatic that knows how to handle all regnode types.
* There is no programmatic way to know if a given regnode is variable length, it is only implied by the code. 

All of these factors make it difficult and error prone to adjust the sizes of regnodes in the compiled regex program and add new functionality, and understand the code.

This patch sequence attempts to resolve these issues: 

* Adds a new function `Perl_regnode_after()` which can be used to reliably find the regnode after a given regnode regardless of its type. 
* Replaces `NEXTOPER()` with `REGNODE_AFTER()` (and a set of specialty variants of `REGNODE_AFTER()`) which should distinguish it from `regnext()`.
* Adds logic to validate the special case variants of `REGNODE_AFTER()` which are used for performance reasons (no need to do run time array looks when we know the result will be zero at compile time).
* Adds a new per-nodetype typedef so that code that it is easy to distinguish between nodes types in the code. For instance if the code is operating on a structure used by the `ANYOF` operator then it can use the typedef `tregnode_ANYOF` instead of `struct charclass` which is shared with multiple other regnodes so that when the given implementation of a node type changes it is easy to find the relevant logic.
* Rename all the `PL_reg` vars which track meta-data about the regnode structures so that they start `PL_regnode_` and add underbars to make them more readable.
* Adds  a new regnode metadata variable `PL_regnode_arg_len_varies[]` which can be used to identify node types whose length is reflected by their internal state. 
* Moves `Perl_regnext()` into reginline.h along with `Perl_regnode_after()` and `Perl_check_regnode()`. The idea being that reginline.h contains inline functions which are strictly used by the regex engine only.

Various sundry changes to facilitate the above changes. 

With these patches it is relatively easy to change the definition of a given regnode and to be able to find the code related to it, and detect what code has broken because it makes unwarranted assumptions about regnode sizes or types. Before this PR when sizes went wrong a bunch of pointer math would end up producing the wrong answer and mayhem would ensue, but nary an assert would fire to show where things went wrong. With it the issues are obvious.  -- This PR *doesnt* include any regnode sizing changes, but a follow up patch does, and these comments are based on experience of resizing the BRANCH nodetype, which is one of the weirder edge cases, and this patch was essential to allowing that to be possible.

The changes in this PR inter mesh with each other. For instance, adding typedefs means we can provide REGNODE_AFTER_type(p,type) which essentially turns into p+=sizeof(type) for the cases where we know we are working with a single well known regnode type.

2022-07-30 19:29 UTC, jkeenan commented
I see several branches with similar names.  How does yours compare to the other branches listed here:
```
$ git branch -a | grep regnode_typedef
  remotes/bram-perl/yves/regnode_typedefs
  remotes/origin/yves/regnode_typedefs
  remotes/pengvado/yves/regnode_typedefs
```

2022-07-30 21:02 UTC, jkeenan requested changes

2022-07-30 21:02 UTC, jkeenan commented on pod/perlreguts.pod
> +overlap conceptually in many places, but where they dont overlap the
missing an apostrophe; s/dont/don't/

2022-07-30 21:02 UTC, jkeenan commented on pod/perlreguts.pod
> +Most regnode types do not create a branch in the exection flow, and
typo: should be `exception`

2022-07-30 21:02 UTC, jkeenan commented on regcomp.h
> + * Note that regnodes can be thought of as nodes in binary tree like structure.
Recommend a hyphen between `tree` and `like`:  `tree-like`

2022-07-31 01:14 UTC, khwilliamson approved these changes
Thank you for this.  

I only found trivial issues.

2022-07-31 01:14 UTC, khwilliamson commented on regcomp.h
> + * else).  To access the immediate successor of a reegnode you should use one
typo: regnode

2022-07-31 01:14 UTC, khwilliamson commented on regcomp.h
> +#define	_REGNODE_AFTER_plus(p,extra)    ((p) + NODE_STEP_REGNODE + (extra))
We probably shouldn't be adding non-conforming symbol names.  `REGNODE_AFTER_PLUS_` should do

2022-07-31 01:14 UTC, khwilliamson commented on regcomp.h
> +/* under DEBUGGING we check that all REGNODE_AFTER style macro did the
*macros

2022-07-31 07:15 UTC, demerphq commented
On Sat, 30 Jul 2022 at 21:29, James E Keenan ***@***.***>
wrote:

> I see several branches with similar names. How does yours compare to the
> other branches listed here:
>
> $ git branch -a | grep regnode_typedef
>   remotes/bram-perl/yves/regnode_typedefs
>   remotes/origin/yves/regnode_typedefs
>   remotes/pengvado/yves/regnode_typedefs
>
> Those are other peoples copies of the branch which they have pulled into
their repo, and then you have pulled from them into yours. Likely theirs is
old. The canonical branch is origin/yves/regnode_typesdef.

Yves
-- 
perl -Mre=debug -e "/just|another|perl|hacker/"

2022-07-31 10:44 UTC, demerphq commented on pod/perlreguts.pod
> +Most regnode types do not create a branch in the exection flow, and
execution actually. :-)

2022-08-01 12:11 UTC, demerphq commented
Hi, I integrated and rebased the requested changes. I also added a new comment with more and better docs. No code changes other than requested in the rebase. Please review the very last commit in the PR.

2022-08-01 12:21 UTC, demerphq commented
A follow up question from this PR for me is whether we should unify the regnode information data into a structure and replace all the PL_regnode_... arrays with something unified. We could even use packed integers and reduce the memory footprint involved, not sure if that would be a win or not.

2022-08-02 06:03 UTC, demerphq commented
@jkeenan and @khwilliamson need approvals from you guys again.

2022-08-02 13:28 UTC, khwilliamson approved these changes

2022-08-02 13:40 UTC, jkeenan approved these changes

2022-08-03 09:07 UTC, merged