Bump IO.pm version to 1.51, due to PR 19663
Perl/perl5 pull request #20201
Opened 2022-08-31 13:23 UTC by sisyphus

IIUC, https://github.com/Perl/perl5/pull/19663 should have bumped IO.pm to version 1.51, because of the alteration it made to dist/IO/poll.h.
But this was overlooked.
Consequently, blead has IO at version 1.50 and CPAN has IO at version 1.50, but they contain different IO/poll.h files.

This PR is intended to correct the earlier oversight.

Cheers,
Rob

2022-08-31 13:43 UTC, haarg commented
Would probably be good to sync all of the IO versions at 1.51

2022-09-02 11:02 UTC, sisyphus commented
I notice that each of my 10 commit messages from yesterday begin with the "=" sign.
I normally specify my commits using <code>--file=msg.txt</code>, but this time I went with <code>-m="the message"</code>.
I'm guessing I should not have used the "=" sign with the -m option.
Anyway - I hope that can be overlooked, and I'll try to remember to always use the <code>--file</code> option in future.

2022-09-02 15:06 UTC, demerphq commented
On Fri, 2 Sept 2022 at 13:02, sisyphus ***@***.***> wrote:

> I notice that each of my 10 commit messages from yesterday begin with the
> "=" sign.
> I normally specify my commits using --file=msg.txt, but this time I went
> with -m="the message".
> I'm guessing I should not have used the "=" sign with the -m option.
> Anyway - I hope that can be overlooked, and I'll try to remember to always
> use the --file option in future.
>
If they have not been merged yet fixing this is relatively easy, just use
git rebase --interactive and the "reword" option.

Yves


-- 
perl -Mre=debug -e "/just|another|perl|hacker/"

2022-09-03 19:06 UTC, jkeenan commented
> On Fri, 2 Sept 2022 at 13:02, sisyphus ***@***.***> wrote: I notice that each of my 10 commit messages from yesterday begin with the "=" sign. I normally specify my commits using --file=msg.txt, but this time I went with -m="the message". I'm guessing I should not have used the "=" sign with the -m option. Anyway - I hope that can be overlooked, and I'll try to remember to always use the --file option in future.
> If they have not been merged yet fixing this is relatively easy, just use git rebase --interactive and the "reword" option. Yves
> […](#)
> -- perl -Mre=debug -e "/just|another|perl|hacker/"

I would also ask that you squash these 11 commits into one (with corrected message).  For two reasons:  (1) There's a common logic to all of them.  (2) When, in the future, we have to bisect the core repository in search of a build or test failure, other things being equal it's better to have a smaller number of commits in the bisection range.

With these updates this p.r. will be mergeable, IMO.

2022-09-03 19:09 UTC, jkeenan requested changes
As mentioned in comments, please squash commits and correct commit message.

2022-09-04 05:44 UTC, sisyphus commented
Offhand, I don't know how to do any of the things being requested.
I suspect that I'm a long way off being able to use --interactive. (I haven't tested, but I gather that it's going to want me to select a suitable text editor - which I probably don't have, and won't know how to use even if I do have one.)
I don't use git; I don't like git; I find it inherently uninteresting; and I doubt that I'm clever enough to make intelligent use of it, anyway.
I don't presently know how to "squash these 11 commits into one", but my inkling is that even I will be able to master that bit.

I'll continue to plug away, and I'll probably get there eventually - though I think it will come in the form of a fresh PR and the closure of this one. 
In the meantime, if someone has the desire and opportunity to fix this PR up, they are welcome to do so.
Or, if someone wants to spend the 10 minutes it will probably take them to prepare a fresh PR for this, then I would urge them to do so, as I'm more than happy to close this.

The only reasons I created this PR are that:
1) I, by chance, noticed the oversight;
2) It was one of my (merged) PRs that had failed to update IO.pm version in the first place;
3) It called for the simplest of changes to one file.

That seemed like just the job for a person of my very limited git capability.
What could possibly go wrong !!  ;-)

Cheers,
Rob

2022-09-04 06:24 UTC, demerphq commented
On Sun, 4 Sept 2022 at 07:44, sisyphus ***@***.***> wrote:

> Offhand, I don't know how to do any of the things being requested.
> I suspect that I'm a long way off being able to use --interactive. (I
> haven't tested, but I gather that it's going to want me to select a
> suitable text editor - which I probably don't have, and won't know how to
> use even if I do have one.)
>
yes it likely will on windows.


> I don't use git; I don't like git; I find it inherently uninteresting; and
> I doubt that I'm clever enough to make intelligent use of it, anyway.
>
I don't buy that last point for a minute. I have interacted with you too
many times to accept that argument. Sorry.

I don't presently know how to "squash these 11 commits into one", but my
> inkling is that even I will be able to master that bit.
>
> I'll continue to plug away, and I'll probably get there eventually -
> though I think it will come in the form of a fresh PR and the closure of
> this one.
> In the meantime, if someone has the desire and opportunity to fix this PR
> up, they are welcome to do so.
> Or, if someone wants to spend the 10 minutes it will probably take them to
> prepare a fresh PR for this, then I would urge them to do so, as I'm more
> than happy to close this.
>
> The only reasons I created this PR are that:
>
>    1. I, by chance, noticed the oversight;
>    2. It was one of my (merged) PRs that had failed to update IO.pm
>    version in the first place;
>    3. It called for the simplest of changes to one file.
>
> That seemed like just the job for a person of my very limited git
> capability.
> What could possibly go wrong !! ;-)
>
Ill save you the lecture on craftsmen and tools and show you one way you
could do it: ;-)

To squash it all down one way would be

git checkout $topic_branch
git fetch
git rebase origin/blead
git reset origin/blead
git commit -a -m'....'
git push -f

There are actually shorter recipes, but i wanted you to see the basics.

If this really is a problem contact me off list and ill sort it for you.

cheers,
Yves




-- 
perl -Mre=debug -e "/just|another|perl|hacker/"

2022-09-04 09:14 UTC, sisyphus commented
> If this really is a problem contact me off list and ill sort it for you.

I'm still pretty good at doing copy'n'paste ;-)
Thanks for that @demerphq  - I don't know how I would have worked that out for myself by perusing the stuff that google turns up.
(The mantra has been saved to a local file, for future reference.)

Fingers crossed.

Cheers,
Rob

2022-09-08 14:09 UTC, jkeenan commented
Branch locally rebased on blead, tested, merged to blead, re-tested, pushed.  Closing ticket.

2022-09-08 14:09 UTC, closed without merging

2022-09-09 00:46 UTC, sisyphus commented
@jkeenan, I had expected that this PR would simply have been merged - rather than subjected to the procedure you outlined.
That's not an issue for me at all - except that if there's something I did (but shouldn't have) or didn't (but should have), please let me know.
Or was it simply that my expectation was a bad one ?
(This is possibly off-topic here and, IMO, there's no obligation to respond to it.)