Small docs clarification on MRO resolve function
Perl/perl5 pull request #20300
Opened 2022-09-14 12:52 UTC by leonerd

Points out that the linear MRO function returns a list of strings.

Before this it wasn't clear to me whether it's a list of string names, or actual HV pointers to stashes.

2022-09-14 12:59 UTC, ilmari requested changes
I think the [perlapi](https://perldoc.perl.org/perlapi#mro_get_linear_isa) entries (in `mro_core.c`) should be updated as well.

2022-09-14 13:47 UTC, leonerd commented
Good plan. Updated. (Should squash before merge)

2022-09-14 14:23 UTC, ilmari commented
There's two entries in `mro_core.c`: `mro_get_linear_isa` as well as `mro_get_linear_isa_dfs`, and I just noticed there's `mro_get_linear_isa_c3` in `ext/mro/mro.xs`.

Maybe the MRO-specific ones shouldn't have all the details, and just link to `mro_get_linear_isa` or `perlmroapi`?

2022-09-16 14:19 UTC, leonerd commented
Eh; I don't feel like a big docs rewrite at this point. This is a 4th(?)-level dependency of something I happen to be working on. I'll just add that they're strings, to each of the locations.

2022-09-16 16:23 UTC, leonerd commented
Ugh, if I update ext/mro/mro.xs then Porting/cmp_version.t gets upset that I didn't bump the version number. I'm not sure I want to bump a version number purely to add a tiny clarification note on the docs of a function almost nobody cares about :P

2022-09-16 18:11 UTC, ilmari commented
> I'm not sure I want to bump a version number purely to add a tiny clarification note on the docs of a function almost nobody cares about :P

Are version numbers that expensive? ;-P

2023-02-08 03:13 UTC, demerphq commented
I updated the version and force pushed this with a better formatted commit message.

2023-02-08 03:13 UTC, demerphq approved these changes

2023-02-08 08:58 UTC, merged