locale.c: Omit final ';' in LC_ALL composite locale
Perl/perl5 pull request #20488
Opened 2022-11-05 20:29 UTC by khwilliamson

When locales for categories differ, LC_ALL needs a way to express the individual components.  Prior to this commit, the aggregation ended with a semi-colon, which is unnecessary.  This commit removes that.

It also moves a loop counter declaration into the loops, now that we have C99, and avoids an extra strlen() call.

2022-11-06 09:26 UTC, demerphq requested changes

2022-11-06 09:26 UTC, demerphq commented on locale.c
> +    for (unsigned i = 0; i < NOMINAL_LC_ALL_INDEX; i++) {
I know it is legal, but could we spell this out fully? it makes me a bit leery to see a raw unsigned, even if it is legal.

2023-01-17 14:12 UTC, jkeenan commented on locale.c
> +    for (unsigned i = 0; i < NOMINAL_LC_ALL_INDEX; i++) {
@khwilliamson, have you had a chance to think about @demerphq's question?

2023-01-31 00:46 UTC, khwilliamson commented
I will replace this PR with an updated one at some point

2023-03-21 17:05 UTC, closed without merging