Fix compilation of -DPERL_MEM_LOG
Perl/perl5 pull request #20542
Opened 2022-11-25 17:50 UTC by khwilliamson

This no longer compiled, giving the error

locale.c:2878:15: error: invalid conversion from ‘const void*’ to ‘void*’ [-fpermissive]

The simple solution is to change memlog to explicitly have a const parameter.

2022-11-25 19:33 UTC, jkeenan commented
> This no longer compiled, giving the error
> 
> locale.c:2878:15: error: invalid conversion from ‘const void*’ to ‘void*’ [-fpermissive]

I can't recall seeing this (build-time, presumably) error.  What configuration options do you use to trigger it.

Also, at what point in the past *did* it compile?  At what commit did it start to fail to compile?

2022-11-28 03:24 UTC, tonycoz commented
> This no longer compiled, giving the error
> 
> locale.c:2878:15: error: invalid conversion from ‘const void*’ to ‘void*’ [-fpermissive]
> 
> The simple solution is to change memlog to explicitly have a const parameter.

The problem here is passing a const pointer to realloc().

Safefree() blindly (and incorrectly) casts away the const, so we don't see similar issues there.

I was working on fixing -Wcast-qual warnings, and had to remove const from a few dynamically allocated pointers.

2023-02-07 13:34 UTC, demerphq approved these changes

2023-02-07 13:35 UTC, demerphq commented
@tonycoz @khwilliamson is this ok to merge?

2023-02-08 04:08 UTC, tonycoz commented
> @tonycoz @khwilliamson is this ok to merge?

No, the dynamically allocated const pointers should be non-const.

2023-02-08 08:28 UTC, demerphq commented
@tonycoz does that mean we should just close this PR? there doesnt seem to be much else in the PR *but* adding const decls.

2023-02-08 08:28 UTC, demerphq requested changes
@khwilliamson tonycoz seems to think this wrong. Can you respond or close the PR?

2023-02-09 03:18 UTC, khwilliamson commented
over taken by events

2023-02-09 03:18 UTC, closed without merging