Gh20724
Perl/perl5 pull request #20725
Opened 2023-01-19 00:30 UTC by hvds

1) Modify recently-added example to use `expect-fail`.
2) Add section "ABOUT BISECTION" to explain the concept and git terminology a bit better.

2023-01-19 00:33 UTC, tonycoz approved these changes

2023-01-19 01:55 UTC, jkeenan requested changes
Other than POD formatting, LGTM

2023-01-19 01:55 UTC, jkeenan commented on Porting/bisect-runner.pl
> +commits earlier than the target commit are "good" commits, those later
My impression is that we generally spell names of other programs with `F<>`, so I would recommend `F<git>` here, and `F<bisect.pl>` in two locations below.

2023-01-19 02:52 UTC, hvds commented
James E Keenan ***@***.***> wrote:
:My impression is that we generally spell names of other programs with `F<>`, so I would recommend `F<git>` here, and `F<bisect.pl>` in two locations below.

I've changed it to use `F<bisect.pl>`.

The phrase "C<git> terminology" is talking about the git ecosystem rather
than the executable, so I'm not convinced that change is as appropriate.

I've also tightened up the wording of the first paragraph some.

2023-01-20 11:36 UTC, hvds commented
Now merged.

2023-01-20 11:36 UTC, closed without merging