perl.h: Make sure PERL_IMPLICIT_CONTEXT doesn't come back
Perl/perl5 pull request #20776
Opened 2023-02-08 14:09 UTC by khwilliamson

This is an obsolete name, retained for back compat with cpan.  Make sure the core doesn't have it defined.

2023-02-09 15:17 UTC, demerphq requested changes

2023-02-09 15:17 UTC, demerphq commented on perl.h
> +#  undef PERL_IMPLICIT_CONTEXT
maybe this should use pragma warn?

2023-02-09 15:17 UTC, demerphq commented on perl.h
> +#  undef PERL_IMPLICIT_CONTEXT
Sorry i mean something like:

```
#ifdef PERL_IMPLICIT_CONTEXT
#praga message("PERL_IMPLICIT_CONTEXT was removed from core perl. It does not do anything. undeffing it for compilation")
#undef PERL_IMPLICIT_CONTEXT
#endif
```

2023-02-10 23:15 UTC, khwilliamson commented on perl.h
> +#  undef PERL_IMPLICIT_CONTEXT
done

2023-02-11 01:01 UTC, demerphq commented on perl.h
> +#  undef PERL_IMPLICIT_CONTEXT
Cool.

2023-02-11 01:01 UTC, demerphq approved these changes

2023-02-11 04:29 UTC, merged