Attribute-Handlers: Add and fix Makefile.PL
Perl/perl5 pull request #20867
Opened 2023-02-28 15:49 UTC by haarg

2023-02-28 15:52 UTC, haarg commented
I think this should really be done for everything in `dist`. As it is, many don't have a Makefile.PL or other packaging files, requiring external repositories to exist to track them. This makes patching the files a horrible pain in the ass, since you have to find the repository that contains the files you care about. But also often those repositories are long dead as the authors have moved on.

2023-02-28 15:52 UTC, demerphq requested changes

2023-02-28 15:52 UTC, demerphq commented on dist/Attribute-Handlers/Makefile.PL
> +  INSTALLDIRS   => INSTALLDIRS => ( "$]" >= 5.011 ? 'site' : 'perl' ),
i think INSTALLDIRS is duplicated.

2023-02-28 15:52 UTC, demerphq commented on dist/Attribute-Handlers/.gitignore
> +!/Makefile.PL
Why the leading slash?

2023-02-28 15:53 UTC, demerphq commented
Can you squash that down @haarg?  5 commits for this seems a lot.  Why not just one?

2023-02-28 15:55 UTC, haarg commented on dist/Attribute-Handlers/Makefile.PL
> +  INSTALLDIRS   => INSTALLDIRS => ( "$]" >= 5.011 ? 'site' : 'perl' ),
Fixed.

2023-02-28 15:57 UTC, haarg commented on dist/Attribute-Handlers/.gitignore
> +!/Makefile.PL
It will only match the file in this immediate directory, rather than recursively. And I only care about the one file. I just always write gitignore statements like this unless there's a good reason not to.

2023-02-28 15:58 UTC, demerphq commented on dist/Attribute-Handlers/.gitignore
> +!/Makefile.PL
Ok, makes sense to me.

2023-02-28 16:00 UTC, demerphq approved these changes

2023-02-28 16:01 UTC, demerphq commented
> I think this should really be done for everything in dist

Concur. How can I help?

2023-02-28 16:24 UTC, jkeenan commented
`MANIFEST` needs updating; then `make test_porting` and it should be good to go.

2023-03-01 10:14 UTC, demerphq commented
See https://github.com/Perl/perl5/issues/20874

2023-03-02 10:28 UTC, demerphq commented
I squashed this down myself.

2023-03-02 12:17 UTC, merged