Permit attributed variables inside signatured subs (Fixes GH #21158)
Perl/perl5 pull request #21159
Opened 2023-06-19 17:07 UTC by leonerd

It's been broken since at least 5.36 and probably older, so I don't feel there's any rush to get this in before 5.38.0, but if folks are happy I guess it could go in.

2023-06-19 17:09 UTC, ilmari requested changes

2023-06-19 17:09 UTC, ilmari commented on t/op/signatures.t
> +ok(defined eval 'sub gt21158 ($x) { my $bar :baz; } "ok"',
Shouldn't that be `gh21158`?

2023-06-19 17:12 UTC, leonerd commented on t/op/signatures.t
> +ok(defined eval 'sub gt21158 ($x) { my $bar :baz; } "ok"',
Ahyes. Force-pushed.

2023-06-19 17:14 UTC, rwp0 commented
Thanks.

May also consider putting this in the PR description: Fixes #21158 

So the PR is linked to issue properly by GitHub.

![image](https://github.com/Perl/perl5/assets/68062695/70af43da-4964-4606-926d-0fb6ee23bf19)

2023-06-19 17:15 UTC, leonerd commented
> May also consider putting this in the PR description: Fixes #21158 (and not just on title)

Oh huh. I didn't realise that made a difference.

2023-06-19 17:19 UTC, rwp0 commented
> > May also consider putting this in the PR description: Fixes #21158 (and not just on title)
> 
> Oh huh. I didn't realise that made a difference.

Thanks, now the issue also appears here in the PR list:

![image](https://github.com/Perl/perl5/assets/68062695/ea02cdf4-820a-4c17-b8f0-c440bca12947)

2023-06-19 17:56 UTC, perigrin commented
My only argument with having this possibly go in with 5.38.0-RC2 is that before we only ever really use non-subroutine attributes (in core) with shared variables so it's fairly uncommon. With `feature 'class'` they're more common as they're the way to add arguments to the class constructor.

Given that `feature 'class'` is experimental though, I don't know that it is compelling at this late stage.

2023-06-19 19:03 UTC, leonerd commented
@perigrin Indeed. It seems fairly rare to encounter it up until now. Perhaps best to wait until 5.39.x then. Shall I tag it defer-next-dev?

2023-06-19 22:29 UTC, tonycoz commented
This might also be a fix for #19245

2023-06-19 22:32 UTC, rwp0 approved these changes

2023-06-19 22:39 UTC, perigrin commented
@leonerd I think that's up to people higher up the p5p food chain than me. I've re-written the demo code I had to avoid the issue so I'm good for the foreseeable future. If 5.40 is the right answer then that's the right answer.

2023-06-23 19:02 UTC, ilmari approved these changes

2023-06-23 19:23 UTC, rwp0 approved these changes

2023-06-23 19:24 UTC, rwp0 commented
Merge in for 5.38.0 🙂

2023-06-29 00:50 UTC, esabol approved these changes

2023-07-10 20:56 UTC, jkeenan commented
> @perigrin Indeed. It seems fairly rare to encounter it up until now. Perhaps best to wait until 5.39.x then. Shall I tag it defer-next-dev?

@leonerd, I've removed the 'defer-next-dev' label.  Is this p.r. ready to merge?

2023-07-12 01:10 UTC, esabol commented
> > @perigrin Indeed. It seems fairly rare to encounter it up until now. Perhaps best to wait until 5.39.x then. Shall I tag it defer-next-dev?
> 
> @leonerd, I've removed the 'defer-next-dev' label. Is this p.r. ready to merge?

One of the "minitests" failed in what seems to be a non-spurious way:
```
# Failed test 1245 - Signatured subroutine permits attributed scalar at op/signatures.t line 1720
# Error was Can't locate attributes.pm in @INC (you may need to install the attributes module) (@INC entries checked: ../lib /home/runner/work/perl5/perl5/cpan/AutoLoader/lib /home/runner/work/perl5/perl5/dist/Carp/lib /home/runner/work/perl5/perl5/dist/PathTools /home/runner/work/perl5/perl5/dist/PathTools/lib /home/runner/work/perl5/perl5/cpan/ExtUtils-Install/lib /home/runner/work/perl5/perl5/cpan/ExtUtils-MakeMaker/lib /home/runner/work/perl5/perl5/cpan/ExtUtils-Manifest/lib /home/runner/work/perl5/perl5/cpan/File-Path/lib /home/runner/work/perl5/perl5/ext/re /home/runner/work/perl5/perl5/dist/Term-ReadLine/lib /home/runner/work/perl5/perl5/dist/Exporter/lib /home/runner/work/perl5/perl5/ext/File-Find/lib /home/runner/work/perl5/perl5/cpan/Text-Tabs/lib /home/runner/work/perl5/perl5/dist/constant/lib /home/runner/work/perl5/perl5/cpan/version/lib /home/runner/work/perl5/perl5/cpan/Getopt-Long/lib /home/runner/work/perl5/perl5/cpan/Text-ParseWords/lib /home/runner/work/perl5/perl5/cpan/ExtUtils-PL2Bat/lib /home/runner/work/perl5/perl5/lib .. . .) at (eval 828) line 1, <$kh> line 382.
```

2023-07-12 01:30 UTC, jkeenan commented
> > > @perigrin Indeed. It seems fairly rare to encounter it up until now. Perhaps best to wait until 5.39.x then. Shall I tag it defer-next-dev?
> > 
> > 
> > @leonerd, I've removed the 'defer-next-dev' label. Is this p.r. ready to merge?
> 
> One of the "minitests" failed in what seems to be a non-spurious way:
> 
> > > Failed test 1245 - Signatured subroutine permits attributed scalar at op/signatures.t line 1720
> > > Error was Can't locate attributes.pm in INC (you may need to install the attributes module) INC entries checked: ../lib /home/runner/work/perl5/perl5/cpan/AutoLoader/lib /home/runner/work/perl5/perl5/dist/Carp/lib /home/runner/work/perl5/perl5/dist/PathTools /home/runner/work/perl5/perl5/dist/PathTools/lib /home/runner/work/perl5/perl5/cpan/ExtUtils-Install/lib /home/runner/work/perl5/perl5/cpan/ExtUtils-MakeMaker/lib /home/runner/work/perl5/perl5/cpan/ExtUtils-Manifest/lib /home/runner/work/perl5/perl5/cpan/File-Path/lib /home/runner/work/perl5/perl5/ext/re /home/runner/work/perl5/perl5/dist/Term-ReadLine/lib /home/runner/work/perl5/perl5/dist/Exporter/lib /home/runner/work/perl5/perl5/ext/File-Find/lib /home/runner/work/perl5/perl5/cpan/Text-Tabs/lib /home/runner/work/perl5/perl5/dist/constant/lib /home/runner/work/perl5/perl5/cpan/version/lib /home/runner/work/perl5/perl5/cpan/Getopt-Long/lib /home/runner/work/perl5/perl5/cpan/Text-ParseWords/lib /home/runner/work/perl5/perl5/cpan/ExtUtils-PL2Bat/lib /home/runner/work/perl5/perl5/lib .. . .) at (eval 828) line 1, <$kh> line 382.

An excellent catch!  @leonerd, can you revise the p.r. to skip tests as needed -- probably something like one of these:
```
$ ack miniperl t/op | ack attributes
t/op/getpid.t:10:	"no dynamic loading on miniperl, no threads/attributes"
t/op/state.t:174:skip "no attributes in miniperl", 3, if is_miniperl;
t/op/state.t:395:        skip_if_miniperl("miniperl can't load attributes.pm", 1)
t/op/attrs.t:9:    skip_all_if_miniperl("miniperl can't load attributes");
t/op/attrhand.t:7:    skip_all_if_miniperl("miniperl can't load attributes");
t/op/decl-refs.t:69:            skip_if_miniperl "No attributes on miniperl", 2;
t/op/decl-refs.t:92:            skip_if_miniperl "No attributes on miniperl", 2;
t/op/attrproto.t:10:    skip_all_if_miniperl("miniperl can't load attributes");
```

2023-08-01 00:53 UTC, jkeenan commented
> > > > @perigrin Indeed. It seems fairly rare to encounter it up until now. Perhaps best to wait until 5.39.x then. Shall I tag it defer-next-dev?
> > > 
> > > 
> > > @leonerd, I've removed the 'defer-next-dev' label. Is this p.r. ready to merge?
> > 
> > 
> > One of the "minitests" failed in what seems to be a non-spurious way:
> > > > Failed test 1245 - Signatured subroutine permits attributed scalar at op/signatures.t line 1720
> > > > Error was Can't locate attributes.pm in INC (you may need to install the attributes module) INC entries checked: ../lib /home/runner/work/perl5/perl5/cpan/AutoLoader/lib /home/runner/work/perl5/perl5/dist/Carp/lib /home/runner/work/perl5/perl5/dist/PathTools /home/runner/work/perl5/perl5/dist/PathTools/lib /home/runner/work/perl5/perl5/cpan/ExtUtils-Install/lib /home/runner/work/perl5/perl5/cpan/ExtUtils-MakeMaker/lib /home/runner/work/perl5/perl5/cpan/ExtUtils-Manifest/lib /home/runner/work/perl5/perl5/cpan/File-Path/lib /home/runner/work/perl5/perl5/ext/re /home/runner/work/perl5/perl5/dist/Term-ReadLine/lib /home/runner/work/perl5/perl5/dist/Exporter/lib /home/runner/work/perl5/perl5/ext/File-Find/lib /home/runner/work/perl5/perl5/cpan/Text-Tabs/lib /home/runner/work/perl5/perl5/dist/constant/lib /home/runner/work/perl5/perl5/cpan/version/lib /home/runner/work/perl5/perl5/cpan/Getopt-Long/lib /home/runner/work/perl5/perl5/cpan/Text-ParseWords/lib /home/runner/work/perl5/perl5/cpan/ExtUtils-PL2Bat/lib /home/runner/work/perl5/perl5/lib .. . .) at (eval 828) line 1, <$kh> line 382.
> 
> An excellent catch! @leonerd, can you revise the p.r. to skip tests as needed -- probably something like one of these:
> 
> ```
> $ ack miniperl t/op | ack attributes
> t/op/getpid.t:10:	"no dynamic loading on miniperl, no threads/attributes"
> t/op/state.t:174:skip "no attributes in miniperl", 3, if is_miniperl;
> t/op/state.t:395:        skip_if_miniperl("miniperl can't load attributes.pm", 1)
> t/op/attrs.t:9:    skip_all_if_miniperl("miniperl can't load attributes");
> t/op/attrhand.t:7:    skip_all_if_miniperl("miniperl can't load attributes");
> t/op/decl-refs.t:69:            skip_if_miniperl "No attributes on miniperl", 2;
> t/op/decl-refs.t:92:            skip_if_miniperl "No attributes on miniperl", 2;
> t/op/attrproto.t:10:    skip_all_if_miniperl("miniperl can't load attributes");
> ```

@leonerd please see above suggestion for revision.

2023-08-01 18:03 UTC, leonerd commented
Repushed; will await CI

2023-08-05 14:06 UTC, rwp0 approved these changes

2023-08-12 14:22 UTC, esabol approved these changes

2023-08-16 22:07 UTC, merged