disable duplicate IRC bot notifications on #p5p
Perl/perl5 pull request #21303
Opened 2023-07-27 16:51 UTC by mauke

Currently every new pull request generates seven lines of activity in irc.perl.org/#p5p that look like this:

    <botifico> [perl5] khwilliamson opened pull request #21302: autodoc: A config.h entry may not clash with perlintern - https://github.com/Perl/perl5/pull/21302
    -!- Pull-Request [~pull-requ@40.84.179.161] has joined #p5p
    <Pull-Request> khwilliamson opened PR #21302
    <Pull-Request> autodoc: A config.h entry may not clash with perlintern
    <Pull-Request> https://github.com/Perl/perl5/pull/21302
    <Pull-Request>
    -!- Pull-Request [~pull-requ@40.84.179.161] has left #p5p []

Six of those are redundant because botifico already handles everything, so comment them out to reduce noise.

(The "merged PR" and "closed PR" cases don't seem to work at all. At least I don't see them in the channel. And I'm not sure why there's an empty line in the output.)

2023-07-27 16:54 UTC, ilmari requested changes

2023-07-27 16:54 UTC, ilmari commented on .github/workflows/irc-notifications.yaml
> +#      - name: irc opened pull request
Urgh, please don't commit commented-out code. It's in git history, we can always revert if we change our mind.

2023-07-29 10:41 UTC, bram-perl approved these changes
LGTM

2023-07-31 23:39 UTC, tonycoz approved these changes

2023-08-05 14:01 UTC, rwp0 approved these changes

2023-08-07 23:42 UTC, merged