Maintainers.pl: use strict/warnings with "our"
Perl/perl5 pull request #21412
Opened 2023-08-21 16:57 UTC by rwp0

Add 2 pragmas, and scope globals with "our".

2023-08-21 19:09 UTC, Leont commented
Have you tried to `perl -c` it? You'll find that `%Maintainers` and `%DistName` also need to be declared ;-)

2023-08-22 10:01 UTC, rwp0 commented
> Have you tried to `perl -c` it? You'll find that `%Maintainers` and `%DistName` also need to be declared 😉

Yes, thanks for the tip (damn [autovivifaction](https://en.wikipedia.org/wiki/Autovivification)).

I'm sorry, unfortunately I'm currently restricted to Windows (I hate that fact).

And WSL doesn't help with `^M` and `\n` DOS/Unix line endings (with IntelliJ IDE's).

Though GitHub Codespaces seem to help with it, will stick to it for a while since everything else seem to fail in various ways.

2023-08-22 10:08 UTC, haarg requested changes

2023-08-22 10:08 UTC, haarg commented on Porting/Maintainers.pl
> +my %DistName;
This is needed externally, it can't be a my variable.

2023-08-22 10:08 UTC, haarg commented on Porting/Maintainers.pl
> +my %Maintainers;
Ditto.

2023-08-22 10:08 UTC, haarg commented on Porting/Maintainers.pl
> +%#!perl
Not sure what this is meant to accomplish.

2023-08-22 10:18 UTC, rwp0 commented
Working on to create a single commit

2023-08-22 10:30 UTC, closed without merging