Move full list of extra_paired_delimiters characters to a better location
Perl/perl5 pull request #22174
Opened 2024-04-25 18:19 UTC by leonerd

feature.pm is probably a bad place for this. It seems more related to the quote-like docs in perlop.pod

Additionally, putting it at the end of the file means most users won't have to scroll past it most of the time.

2024-04-25 18:21 UTC, ilmari approved these changes

2024-04-25 19:06 UTC, haarg requested changes

2024-04-25 19:06 UTC, haarg commented on pod/perlop.pod
> +a full list, see the L</APPENDIX> at the end of this document.
This should link directly to the `List of Extra Paired Delimiters` section.

2024-04-25 19:06 UTC, haarg commented on regen/feature.pl
> -The complete list of accepted paired delimiters as of Unicode 14.0 is:
There should be a link here to the new location of the list.

2024-04-25 23:34 UTC, rwp0 commented on pod/perlop.pod
> + 👉 👈   U+1F449, U+1F448 WHITE RIGHT/LEFT POINTING BACKHAND INDEX
this is the best one 🙂

2024-04-26 09:19 UTC, leonerd commented
Pod links added, and `=encoding` line fixed.

2024-04-26 13:55 UTC, haarg approved these changes

2024-04-26 14:04 UTC, merged