perlapi: Combine langinfo()-like forms
Perl/perl5 pull request #22342
Opened 2024-06-21 20:39 UTC by khwilliamson

Having one group containing the descriptions of all closely related functions makes the pod more compact and makes maintenance easier; fixes only need to be applied in one place.  And it encourages the documentation authors to compare and contrast the variants, paying closer attention to the subtle differences between them.

And it is easier for the reader to choose the variant that is best for their current purpose, rather than hopping around the file, unsure if the current text is identical to that found elsewhere, or if there is a subtle nuance (or three).

2024-06-22 12:41 UTC, jkeenan requested changes
Okay other than as noted below.

2024-06-22 12:41 UTC, jkeenan commented on locale.c
> +C<setlocale>, or other locale change.  C<sv_langinfo> side steps this problem
I think `side steps` should be just one word.

2024-06-22 20:04 UTC, khwilliamson commented on locale.c
> +C<setlocale>, or other locale change.  C<sv_langinfo> side steps this problem
done

2024-06-23 12:20 UTC, jkeenan approved these changes

2024-06-23 13:01 UTC, merged