perldelta: Add notes about recent op_dump() and xop_dump additions
Perl/perl5 pull request #22583
Opened 2024-09-09 12:59 UTC by leonerd

---------------------------------------------------------------------------------
* [ ] This set of changes requires a perldelta entry, and it is included.
* [ ] This set of changes requires a perldelta entry, and I need help writing it.
* [ ] This set of changes does not require a perldelta entry.

None of the above. This set of changes *is* the perldelta entry ;)

2024-09-09 15:32 UTC, khwilliamson requested changes
after minor change, I approve this PR

2024-09-09 15:32 UTC, khwilliamson commented on pod/perldelta.pod
> +C<op_dump()> now also has facility to print extra debugging information about
s/facility/the &/

2024-09-09 23:07 UTC, leonerd commented on pod/perldelta.pod
> +C<op_dump()> now also has facility to print extra debugging information about
Fixed

2024-09-10 02:31 UTC, khwilliamson approved these changes

2024-09-10 12:41 UTC, merged