Update POD for Newx/Renew/Safefree vs libc analogs about heap corruption
Perl/perl5 pull request #22682
Opened 2024-10-20 16:18 UTC by bulk88

This isn't documented anywhere except in perlapi, in the per-macro/per-function section. A seasoned dev, will read perlguts ONCE, write code, then pass a Newx() pointer, to some 3rd party library or native OS API, and then instant disaster, or invisible disaster. If Newx() and libc malloc() pointers are interchangeable, on ONE particular OS, with ONE particular perl build, with ONE particular set of build flags, that is undefined behavior. Have fun with #define USE_MDH or -DUSE_MDH or -DDEBUGGING or #define MYMALLOC -DMYMALLOC.

Also, for anyone reading this in the future.

DO NOT EVER DOCUMENT the permutations where Newx() is libc malloc().

Perl core reserves the right, to separate Newx() and malloc(), at any time in a maint release if there are technical reasons to do so.

Also libperl.so/.dll embedders, if libperl is unloaded from the process, and deallocs all Newx() blocks globally, and a 3rd party library still loaded in the process, thinking it owns that "malloc()" block, that was given ownership of, in 3rd party lib API contract, SEGV time.

TODO: fill description here

---------------------------------------------------------------------------------
* This set of changes requires a perldelta entry, and it is included.
* This set of changes requires a perldelta entry, and I need help writing it.
* This set of changes does not require a perldelta entry.

2024-11-27 01:22 UTC, khwilliamson requested changes

2024-11-27 01:22 UTC, khwilliamson commented on pod/perldelta.pod
> +C<Safefree> vs C<malloc>, C<realloc>, and C<free> not allowed, and mixing
missing the verb `are` here

2024-11-28 19:05 UTC, Leont commented
Yeah, this is an interesting footgun that does deserve being document.

2024-12-19 09:13 UTC, bulk88 commented on pod/perldelta.pod
> +C<Safefree> vs C<malloc>, C<realloc>, and C<free> not allowed, and mixing
repushed with grammer fix and rebase

2024-12-19 19:45 UTC, merged