Simplify the recommended alternatives to rand()
Perl/perl5 pull request #22873
Opened 2024-12-23 17:11 UTC by robrwo

The CPAN Security Group (CPANSec) is currently working on guides to generating security-quality random data.  We are focusing on modules that have secure defaults and are fairly lightweight.

We would like to change the recommended modules to ones that we think are better options.

Crypt::URandom is pure-perl, has fewer prerequisites than Crypt::Random, and works with Windows.

Crypt::PRNG has secure defaults and methods for generating different kinds of random data.

Math::Random::Secure has a lot of prerequisites and in the end is just relying on /dev/urandom, like Crypt::URandom does.

Math::TrulyRandom is from 1996, and it's unclear how well that technique will work on modern systems, especially VMs and containers.

2024-12-24 22:46 UTC, jkeenan commented
We will need to get this p.r. to pass t/porting/podcheck.t before we can proceed further.

2024-12-25 11:04 UTC, robrwo commented
> We will need to get this p.r. to pass t/porting/podcheck.t before we can proceed further.

The podchecker utility installed with Perl says it's ok.

When I run it I get a compilation error that seems to have nothing to do with my change:
> porting/podcheck.t .. Can't locate Carp.pm in @INC (you may need to install the Carp module) (@INC entries checked: ../lib) at porting/podcheck.t line 17.
BEGIN failed--compilation aborted at porting/podcheck.t line 17.

2024-12-25 11:10 UTC, Grinnz commented
The failure is noted in the github actions run, it is because the pod checker must be told about the new non-core modules you are linking to:

```
#   "Apparent broken link"
#     to "Crypt::URandom" near line 6672 of pod/perlfunc.pod
#     to "Crypt::PRNG" near line 6674 of pod/perlfunc.pod
# See end of this test output for your options on silencing this
# 
# HOW TO GET porting/podcheck.t TO PASS
# 
# There was 1 file that had new potential problems identified.
# Some of them may be real, and some of them may be false positives because
# this program isn't as smart as it likes to think it is.  You can teach this
# program to ignore the issues it has identified, and hence pass, by doing the
# following:
# 
# 1) If a problem is about a link to an unknown module or man page that
#    you know exists, re-run the command something like:
#       ./perl -I../lib porting/podcheck.t --add-link { MODULE | man_page ... }
```

2024-12-26 13:20 UTC, robrwo commented
I've updated it, and also updated other references to Math::TrulyRandom.

2024-12-28 11:25 UTC, robrwo commented
The only failing tests are cygwin, which I think has nothing to do with the POD changes.

2025-04-01 19:15 UTC, jkeenan requested changes
perlfaq is maintained upstream on CPAN.  So changes to its text should first be submitted to that distribution's [issue tracker](https://github.com/perl-doc-cats/perlfaq/issues).

2025-04-02 15:41 UTC, robrwo commented
> perlfaq is maintained upstream on CPAN. So changes to its text should first be submitted to that distribution's [issue tracker](https://github.com/perl-doc-cats/perlfaq/issues).

Ok. https://github.com/perl-doc-cats/perlfaq/pull/143

2025-04-02 20:25 UTC, jkeenan commented
I'm now satisfied with the structure of the pull request.  I don't know enough about `rand()` to comment on the content.

2025-04-08 14:48 UTC, robrwo commented
> > perlfaq is maintained upstream on CPAN. So changes to its text should first be submitted to that distribution's [issue tracker](https://github.com/perl-doc-cats/perlfaq/issues).
> 
> Ok. [perl-doc-cats/perlfaq#143](https://github.com/perl-doc-cats/perlfaq/pull/143)

This has been merged.

2025-05-04 22:03 UTC, khwilliamson commented
@robrwo Please do `cd t; ./perl -I../lib porting/podcheck.t --regen` and commit the changes, and repush

2025-05-04 23:19 UTC, khwilliamson approved these changes

2025-06-13 08:27 UTC, robrwo commented
What's delaying this?

It's mid-2025 and the current POD is outdated.

2025-06-13 12:08 UTC, thibaultduponchelle commented
The change on perlfaq was merged [upstream](https://github.com/perl-doc-cats/perlfaq) but did not reach CPAN yet, so it will be integrated later. This point fixes the "requested change" from @jkeenan 

Merging this important security related recommendation on usage of alternative modules to be used for cryptographically secure random data generation.

2025-06-13 12:09 UTC, merged